# Generated by Django 5.2.1 on 2025-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('uses', models.TextField()),
                ('growing_regions', models.TextField()),
                ('climate', models.TextField()),
                ('harvest_time', models.CharField(max_length=100)),
                ('water_needs', models.CharField(max_length=100)),
                ('sunlight', models.CharField(max_length=100)),
                ('clipart', models.ImageField(upload_to='crop_cliparts/')),
            ],
        ),
    ]
