# Generated by Django 5.2.1 on 2025-05-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spacing', models.CharField(blank=True, max_length=50)),
                ('harvest_time', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='crops/')),
            ],
        ),
    ]
