# Generated by Django 5.2.1 on 2025-05-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='fertiliser_tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='growth_stages',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='pest_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='plant_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_season',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crop',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crop',
            name='sunlight_needs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crop',
            name='watering_needs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='harvest_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='spacing',
            field=models.CharField(max_length=100),
        ),
    ]
